spring:
  datasource:
    url: jdbc:mysql://localhost:3306/projekt_mieszkania?serverTimezone=Europe/Warsaw
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080